// config.js — Mapa emocional de cada nivel de estrés
// Modifica estos valores para ajustar la experiencia

const NIVELES = {
  1: {
    nombre:    "Zenito",
    desc:      "Presencia plena · Flujo natural · Ecuanimidad interior",
    estado:    "sistema nervioso en reposo",
    // Paleta visual
    color_bg:       "#060d10",
    color_accent:   "#7ecfb3",
    color_fog:      "#1a4a3e",
    // Geometría 3D
    mesh_speed:     0.0015,
    mesh_scale:     1.0,
    mesh_distort:   0.08,
    mesh_color:     0x4fc0a0,
    wireframe:      false,
    // Partículas
    particle_count: 120,
    particle_speed: 0.0003,
    particle_size:  1.2,
    particle_color: "#7ecfb3",
    // Canvas BG
    bg_hue_base:    170,
    bg_hue_range:   20,
    bg_speed:       0.0003,
    bg_complexity:  3,
    // Audio Tone.js
    audio_synth:    "sine",
    audio_reverb:   0.85,
    audio_base_hz:  [110, 165, 220, 330],
    audio_interval: 4000,
    audio_volume:   -18,
  },
  2: {
    nombre:    "Alerta leve",
    desc:      "Atención activada · Foco sostenido · Energía disponible",
    estado:    "activación simpática incipiente",
    color_bg:       "#0d0e06",
    color_accent:   "#d4c44a",
    color_fog:      "#3a3a10",
    mesh_speed:     0.003,
    mesh_scale:     1.1,
    mesh_distort:   0.2,
    mesh_color:     0xc8b830,
    wireframe:      false,
    particle_count: 200,
    particle_speed: 0.0007,
    particle_size:  1.0,
    particle_color: "#d4c44a",
    bg_hue_base:    55,
    bg_hue_range:   25,
    bg_speed:       0.0007,
    bg_complexity:  5,
    audio_synth:    "triangle",
    audio_reverb:   0.6,
    audio_base_hz:  [130, 195, 260, 390, 520],
    audio_interval: 2800,
    audio_volume:   -14,
  },
  3: {
    nombre:    "Tensión",
    desc:      "Carga acumulada · Umbral de presión · Respuesta de alerta",
    estado:    "cortisol elevado · ritmo cardíaco acelerado",
    color_bg:       "#0f0800",
    color_accent:   "#e87830",
    color_fog:      "#4a2010",
    mesh_speed:     0.006,
    mesh_scale:     1.2,
    mesh_distort:   0.45,
    mesh_color:     0xd05818,
    wireframe:      false,
    particle_count: 340,
    particle_speed: 0.0014,
    particle_size:  0.9,
    particle_color: "#e87830",
    bg_hue_base:    25,
    bg_hue_range:   30,
    bg_speed:       0.0015,
    bg_complexity:  7,
    audio_synth:    "sawtooth",
    audio_reverb:   0.4,
    audio_base_hz:  [150, 225, 300, 450, 600],
    audio_interval: 1800,
    audio_volume:   -10,
  },
  4: {
    nombre:    "Estrés agudo",
    desc:      "Desbordamiento cognitivo · Hipervigilancia · Respuesta de pánico",
    estado:    "sistema nervioso en crisis",
    color_bg:       "#100004",
    color_accent:   "#e0305a",
    color_fog:      "#500020",
    mesh_speed:     0.012,
    mesh_scale:     1.4,
    mesh_distort:   0.8,
    mesh_color:     0xc01840,
    wireframe:      true,
    particle_count: 550,
    particle_speed: 0.0025,
    particle_size:  0.7,
    particle_color: "#e0305a",
    bg_hue_base:    345,
    bg_hue_range:   25,
    bg_speed:       0.003,
    bg_complexity:  10,
    audio_synth:    "square",
    audio_reverb:   0.25,
    audio_base_hz:  [80, 160, 240, 480, 720, 960],
    audio_interval: 900,
    audio_volume:   -6,
  },
  5: {
    nombre:    "Saturación",
    desc:      "Colapso sensorial · Disociación · Umbral de quiebre",
    estado:    "sistema nervioso colapsado",
    color_bg:       "#05000f",
    color_accent:   "#8844cc",
    color_fog:      "#200040",
    mesh_speed:     0.022,
    mesh_scale:     1.8,
    mesh_distort:   1.4,
    mesh_color:     0x6622aa,
    wireframe:      true,
    particle_count: 800,
    particle_speed: 0.004,
    particle_size:  0.5,
    particle_color: "#8844cc",
    bg_hue_base:    270,
    bg_hue_range:   40,
    bg_speed:       0.005,
    bg_complexity:  14,
    audio_synth:    "square",
    audio_reverb:   0.12,
    audio_base_hz:  [60, 90, 180, 270, 540, 810, 1080],
    audio_interval: 450,
    audio_volume:   -3,
  },
};

window.NIVELES = NIVELES;
